/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JednostkaGui.java
 *
 * Created on 2011-04-23, 23:14:45
 */

package forms;

import beans.Jednostka;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mariusz
 */
public class JednostkaGui extends javax.swing.JDialog {

    private Integer idpress;

    /** Creates new form JednostkaGui */
    public JednostkaGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaJednostek();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldJednostka = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        Nowy = new javax.swing.JButton();
        Edytuj = new javax.swing.JButton();
        Usun = new javax.swing.JButton();
        Zapisz = new javax.swing.JButton();
        Zamknij = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jednostki miary");

        jLabel1.setText("Jednostka miary");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Nowy.setText("Nowy");
        Nowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NowyActionPerformed(evt);
            }
        });

        Edytuj.setText("Edytuj");
        Edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytujActionPerformed(evt);
            }
        });

        Usun.setText("Usuń");
        Usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsunActionPerformed(evt);
            }
        });

        Zapisz.setText("Zapisz");
        Zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZapiszActionPerformed(evt);
            }
        });

        Zamknij.setText("Zamknij");
        Zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJednostka, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nowy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(Edytuj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(Usun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(Zapisz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(Zamknij, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldJednostka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(Nowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Edytuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Usun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zapisz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zamknij)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NowyActionPerformed
        idpress = 0;
        jTextEditable(true);
        this.jTextFieldJednostka.setText(null);
        this.Nowy.setEnabled(false);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(true);
    }//GEN-LAST:event_NowyActionPerformed

    private void EdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytujActionPerformed
        jTextEditable(true);
        this.Nowy.setEnabled(false);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(true);
}//GEN-LAST:event_EdytujActionPerformed

    private void UsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsunActionPerformed
        int usun = JOptionPane.showConfirmDialog(null, "Czy na pewno usunąc wpis?");
        if (usun == 0) {
            Jednostka objJednostka = new Jednostka();
            objJednostka.setId(idpress);
            objJednostka.usunJednostke();
            ListaJednostek();
        }
}//GEN-LAST:event_UsunActionPerformed

    private void ZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapiszActionPerformed
        Jednostka objJednostka = new Jednostka();
        objJednostka.setJednostka_m(this.jTextFieldJednostka.getText());
        if (idpress == 0) {
            objJednostka.dodajJednostke();
        } else {
            objJednostka.poprawJednostke(idpress);
        }
        ListaJednostek();
}//GEN-LAST:event_ZapiszActionPerformed

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZamknijActionPerformed
        this.dispose();
}//GEN-LAST:event_ZamknijActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        this.Nowy.setEnabled(true);
        this.Edytuj.setEnabled(true);
        this.Usun.setEnabled(true);
        this.Zapisz.setEnabled(false);
        int rec = this.jTable1.getSelectedRow();
        idpress = Integer.parseInt(jTable1.getValueAt(rec, 0).toString());

        Jednostka objJednostka = new Jednostka();
        objJednostka.znajdzJednostke(idpress);

        this.jTextFieldJednostka.setText(objJednostka.getJednostka_m());

        jTextEditable(false);
    }//GEN-LAST:event_jTable1MousePressed

    public void ListaJednostek() {
        DefaultTableModel table = new DefaultTableModel();
        Jednostka objJednostka = new Jednostka();
        ArrayList<Jednostka> listaJednostek = new ArrayList();
        listaJednostek = objJednostka.ListaJednostek();

        table.addColumn("id");
        table.addColumn("Jednostka miary");
        table.setRowCount(listaJednostek.size());
        int i = 0;
        for (Jednostka x : listaJednostek) {
            table.setValueAt(x.getId(), i, 0);
            table.setValueAt(x.getJednostka_m(), i, 1);
            i++;
        }

        this.jTable1.setModel(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTextEditable(false);

        this.Nowy.setEnabled(true);
        this.Edytuj.setEnabled(false);
        this.Usun.setEnabled(false);
        this.Zapisz.setEnabled(false);

        this.jTextFieldJednostka.setText(null);

    }

    public void jTextEditable(boolean a) {

        if (a) {
            this.jTextFieldJednostka.setEditable(true);
            } else {
            this.jTextFieldJednostka.setEditable(false);
            }
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JednostkaGui dialog = new JednostkaGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edytuj;
    private javax.swing.JButton Nowy;
    private javax.swing.JButton Usun;
    private javax.swing.JButton Zamknij;
    private javax.swing.JButton Zapisz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldJednostka;
    // End of variables declaration//GEN-END:variables

}
