/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KontrahentListaGui.java
 *
 * Created on 2011-05-18, 19:23:33
 */

package forms;

import beans.Faktura;
import beans.Kontrahent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariusz
 */
public class KontrahentListaGui extends javax.swing.JDialog {

    private int idpress;
    private FakturaGui fakgui;
    private Faktura fak;

    /** Creates new form KontrahentListaGui */
    public KontrahentListaGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaKontrahentow();
        this.jButtonWybierz.setEnabled(false);
    }

    public Faktura getFak() {
        return fak;
    }

    public void setFak(Faktura fak) {
        this.fak = fak;
    }

    public FakturaGui getFakgui() {
        return fakgui;
    }

    public void setFakgui(FakturaGui fakgui) {
        this.fakgui = fakgui;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnuluj = new javax.swing.JButton();
        jButtonWybierz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAnuluj.setText("Anuluj");
        jButtonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnulujActionPerformed(evt);
            }
        });

        jButtonWybierz.setText("Wybierz");
        jButtonWybierz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWybierzActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonWybierz)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnuluj)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWybierz)
                    .addComponent(jButtonAnuluj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnulujActionPerformed
        this.dispose();
}//GEN-LAST:event_jButtonAnulujActionPerformed

    private void jButtonWybierzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWybierzActionPerformed

        Kontrahent objKontrahent = new Kontrahent();
        objKontrahent.znajdzKontrahenta(idpress);

        this.fak.setId_kontrahent(objKontrahent.getId());
        this.fakgui.ustawNazweKontrahenta(objKontrahent.getNazwa(), objKontrahent.getKod() + " " + objKontrahent.getMiasto(), objKontrahent.getUlica());

        this.dispose();
}//GEN-LAST:event_jButtonWybierzActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        this.jButtonWybierz.setEnabled(true);

        int rec = this.jTable1.getSelectedRow();
        idpress = Integer.parseInt(jTable1.getValueAt(rec, 0).toString());

}//GEN-LAST:event_jTable1MousePressed


    public void ListaKontrahentow() {
        DefaultTableModel table = new DefaultTableModel();
        Kontrahent objKontrahent = new Kontrahent();
        ArrayList<Kontrahent> listaKontrahentow = new ArrayList();
        listaKontrahentow = objKontrahent.ListaKontrahentów();

        table.addColumn("id");
        table.addColumn("Skrót");
        table.addColumn("Nazwa");
        table.addColumn("NIP");
        table.setRowCount(listaKontrahentow.size());
        int i = 0;
        //System.out.println("lista size = " + lista3.size());
        for (Kontrahent x : listaKontrahentow) {
            table.setValueAt(x.getId(), i, 0);
            table.setValueAt(x.getSkrot(), i, 1);
            table.setValueAt(x.getNazwa(), i, 2);
            table.setValueAt(x.getNip(), i, 3);
            i++;
        }

        this.jTable1.setModel(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);



    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KontrahentListaGui dialog = new KontrahentListaGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnuluj;
    private javax.swing.JButton jButtonWybierz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
