/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TowarLista.java
 *
 * Created on 2011-05-10, 22:15:15
 */

package forms;

import beans.Faktura;
import beans.Pozycja;
import beans.Towar;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariusz
 */
public class TowarListaGui extends javax.swing.JDialog {
    private int idpress;
    private FakturaGui fakgui;
    private Faktura fak;

    /** Creates new form TowarLista */
    public TowarListaGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ListaTowarow();
        this.jButtonWybierz.setEnabled(false);
     
    }

    public Faktura getFak() {
        return fak;
    }

    public void setFak(Faktura fak) {
        this.fak = fak;
    }

    public FakturaGui getFakgui() {
        return fakgui;
    }

    public void setFakgui(FakturaGui fakgui) {
        this.fakgui = fakgui;
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonWybierz = new javax.swing.JButton();
        jButtonAnuluj = new javax.swing.JButton();
        jTextFieldIlosc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonWybierz.setText("Wybierz");
        jButtonWybierz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWybierzActionPerformed(evt);
            }
        });

        jButtonAnuluj.setText("Anuluj");
        jButtonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnulujActionPerformed(evt);
            }
        });

        jLabel1.setText("Ilość");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIlosc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonWybierz)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnuluj)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWybierz)
                    .addComponent(jButtonAnuluj)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIlosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnulujActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAnulujActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

        this.jButtonWybierz.setEnabled(true);
        int rec = this.jTable1.getSelectedRow();
        idpress = Integer.parseInt(jTable1.getValueAt(rec, 0).toString());

        //System.out.print(idpress);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButtonWybierzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWybierzActionPerformed
        Pozycja poz = new Pozycja();
        Towar tow = new Towar();
        tow.znajdzTowar(idpress);
        
        poz.setNazwa(tow.getNazwa());
        poz.setPkwiu(tow.getPkwiu());
        poz.setJednm(String.valueOf(tow.getJednm()));
        poz.setIlosc(Double.parseDouble(this.jTextFieldIlosc.getText()));
        poz.setVat_opis(String.valueOf(tow.getVat()));

        NumberFormat nf = NumberFormat.getInstance();
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(2);
        nf.setGroupingUsed(false);

        poz.setCena_netto(tow.getCena_netto());
        poz.setCena_brutto(tow.getCena_brutto());        
        poz.setWartosc_netto(Double.parseDouble((nf.format(tow.getCena_netto()*poz.getIlosc())).replaceAll(",", ".")));
        poz.setWartosc_brutto(Double.parseDouble((nf.format(tow.getCena_netto()*poz.getIlosc()*(100 + tow.getVat())/100)).replaceAll(",", ".")));
        poz.setVat(poz.getWartosc_brutto() - poz.getWartosc_netto());

        this.fak.dodajPozycje(poz);
        this.fakgui.ListaPozycji();
        
        this.dispose();
        //this.fak.setId_kontrahent(idpress);
        //this.fak.setNr("z okna wyzej");
    }//GEN-LAST:event_jButtonWybierzActionPerformed


     public void ListaTowarow() {
        DefaultTableModel table = new DefaultTableModel();
        Towar objTowar = new Towar();
        ArrayList<Towar> listaTowarow = new ArrayList();
        listaTowarow = objTowar.ListaTowarow();

        table.addColumn("id");
        table.addColumn("Skrót");
        table.addColumn("Nazwa");
        table.addColumn("Cena Netto");
        table.addColumn("VAT");
        table.addColumn("Cena Brutto");
        table.setRowCount(listaTowarow.size());
        int i = 0;

        for (Towar x : listaTowarow) {
            table.setValueAt(x.getId(), i, 0);
            table.setValueAt(x.getSkrot(), i, 1);
            table.setValueAt(x.getNazwa(), i, 2);
            table.setValueAt(x.getCena_netto(), i, 3);
            table.setValueAt(x.getVat(), i, 4);
            table.setValueAt(x.getCena_brutto(), i, 5);
            i++;
        }

        this.jTable1.setModel(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);


    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TowarListaGui dialog = new TowarListaGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnuluj;
    private javax.swing.JButton jButtonWybierz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldIlosc;
    // End of variables declaration//GEN-END:variables

}
