/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ZestawienieGui.java
 *
 * Created on 2011-05-20, 10:05:25
 */

package forms;

import beans.Faktura;
import beans.Kontrahent;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mariusz
 */
public class ZestawienieGui extends javax.swing.JDialog {

    /** Creates new form ZestawienieGui */
    public ZestawienieGui(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ZestawienieSprzedazy();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonZamknij = new javax.swing.JButton();
        jLabel1Razem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zestawienie sprzedaży");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonZamknij.setText("Zamknij");
        jButtonZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZamknijActionPerformed(evt);
            }
        });

        jLabel1Razem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1Razem.setText("Razem sprzedaż: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(jButtonZamknij, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1Razem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1Razem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonZamknij)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZamknijActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZamknijActionPerformed

        public void ZestawienieSprzedazy() {
        DefaultTableModel table = new DefaultTableModel();
        Faktura objFaktura = new Faktura();
        ArrayList<Faktura> listaFaktur = new ArrayList();
        listaFaktur = objFaktura.ListaFaktur();

        table.addColumn("id");
        table.addColumn("Kontrahent");
        table.addColumn("Nr faktury");
        table.addColumn("Data wystawienie");
        table.addColumn("Wartość netto");
        table.addColumn("VAT");
        table.addColumn("Wartość brutto");
        table.setRowCount(listaFaktur.size());

        NumberFormat nf = NumberFormat.getInstance();
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(2);

        int i = 0;
        double razem = 0.0;

        for (Faktura x : listaFaktur) {
            table.setValueAt(x.getId(), i, 0);

            Kontrahent kon = new Kontrahent();
            kon.znajdzKontrahenta(x.getId_kontrahent());

            table.setValueAt(kon.getNazwa(), i, 1);
            table.setValueAt(x.getNr(), i, 2);
            table.setValueAt(x.getData_wystawienie(), i, 3);

            //ArrayList<Pozycja> lista = new ArrayList();
            //lista = x.getLista_pozycji();

            //double netto = 0.0;
            //double vat = 0.0;
            //double brutto = 0.0;

            //for (Pozycja y : lista) {
            //netto = netto + y.getWartosc_netto();
           // vat = vat + y.getVat();
            //brutto = brutto + y.getWartosc_brutto();
            //}

            table.setValueAt(nf.format(x.getWartosc_netto()), i, 4);
            table.setValueAt(nf.format(x.getWartosc_vat()), i, 5);
            table.setValueAt(nf.format(x.getWartosc_brutto()), i, 6);
            razem = razem + x.getWartosc_brutto();
            i++;
        }

        nf.setGroupingUsed(true);
        this.jLabel1Razem.setText("Razem sprzedaż: " + nf.format(razem).toString() + " zł");

        this.jTable1.setModel(table);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);        
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZestawienieGui dialog = new ZestawienieGui(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonZamknij;
    private javax.swing.JLabel jLabel1Razem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
